databases:
  - name: postgres
    ipAllowList: []

services:
  - type: web
    name: rails
    env: ruby
    buildCommand: "toy_app/bin/render-build.sh"
    startCommand: bundle exec rails s
    envVars:
      RAILS_MASTER_KEY: ""
      DATABASE_URL:
        from:
          Database:
            name: postgres
            property: connectingString
  - type: redis
    name: redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: noeviction